export const recommendedSources = [
  {
    rank: 1,
    priority: 1,
    name: "OpenAI News",
    slug: "openai-news",
    siteUrl: "https://openai.com/news/",
    kind: "web" as const,
    category: "AI",
    quality: "primary" as const,
    description: "First-party OpenAI product, research, safety, and company announcements.",
    tags: ["AI", "models", "agents", "research"],
  },
  {
    rank: 2,
    priority: 1,
    name: "Anthropic News",
    slug: "anthropic-news",
    siteUrl: "https://www.anthropic.com/news",
    kind: "web" as const,
    category: "AI",
    quality: "primary" as const,
    description: "First-party Anthropic model, research, safety, and product updates.",
    tags: ["AI", "Claude", "agents", "safety"],
  },
  {
    rank: 3,
    priority: 1,
    name: "Google DeepMind",
    slug: "google-deepmind",
    siteUrl: "https://deepmind.google/discover/blog/",
    kind: "web" as const,
    category: "AI Research",
    quality: "primary" as const,
    description: "DeepMind research, model releases, scientific advances, and technical work.",
    tags: ["AI", "research", "science", "models"],
  },
  {
    rank: 4,
    priority: 1,
    name: "Meta AI",
    slug: "meta-ai",
    siteUrl: "https://ai.meta.com/blog/",
    kind: "web" as const,
    category: "AI",
    quality: "primary" as const,
    description: "First-party Meta AI research, open models, infrastructure, and product work.",
    tags: ["AI", "open models", "research", "infrastructure"],
  },
  {
    rank: 5,
    priority: 1,
    name: "Hugging Face Blog",
    slug: "hugging-face-blog",
    siteUrl: "https://huggingface.co/blog",
    feedUrl: "https://huggingface.co/blog/feed.xml",
    kind: "rss" as const,
    category: "AI",
    quality: "primary" as const,
    description: "Open-source AI models, datasets, tooling, inference, and community research.",
    tags: ["AI", "open source", "models", "datasets"],
  },
  {
    rank: 6,
    priority: 1,
    name: "NVIDIA Technical Blog",
    slug: "nvidia-technical-blog",
    siteUrl: "https://developer.nvidia.com/blog/",
    feedUrl: "https://developer.nvidia.com/blog/feed/",
    kind: "rss" as const,
    category: "AI Infrastructure",
    quality: "primary" as const,
    description: "GPU computing, AI systems, inference, CUDA, robotics, and accelerated computing.",
    tags: ["AI", "GPU", "inference", "CUDA", "infrastructure"],
  },
  {
    rank: 7,
    priority: 1,
    name: "Google Research",
    slug: "google-research",
    siteUrl: "https://research.google/blog/",
    feedUrl: "https://research.google/blog/rss/",
    kind: "rss" as const,
    category: "AI Research",
    quality: "primary" as const,
    description: "Google research across machine learning, systems, security, science, and computing.",
    tags: ["research", "AI", "systems", "science"],
  },
  {
    rank: 8,
    priority: 1,
    name: "Microsoft Research",
    slug: "microsoft-research",
    siteUrl: "https://www.microsoft.com/en-us/research/blog/",
    feedUrl: "https://www.microsoft.com/en-us/research/feed/",
    kind: "rss" as const,
    category: "AI Research",
    quality: "primary" as const,
    description: "Microsoft research in AI, systems, programming languages, security, and science.",
    tags: ["research", "AI", "systems", "security"],
  },
  {
    rank: 9,
    priority: 2,
    name: "BAIR Blog",
    slug: "bair-blog",
    siteUrl: "https://bair.berkeley.edu/blog/",
    feedUrl: "https://bair.berkeley.edu/blog/feed.xml",
    kind: "rss" as const,
    category: "AI Research",
    quality: "expert" as const,
    description: "Berkeley AI Research articles covering machine learning, robotics, and AI research.",
    tags: ["research", "machine learning", "robotics", "AI"],
  },
  {
    rank: 10,
    priority: 1,
    name: "GitHub Blog",
    slug: "github-blog",
    siteUrl: "https://github.blog/",
    feedUrl: "https://github.blog/feed/",
    kind: "rss" as const,
    category: "Engineering",
    quality: "primary" as const,
    description: "GitHub engineering, developer tools, open source, security, and platform updates.",
    tags: ["engineering", "GitHub", "open source", "developer tools"],
  },
  {
    rank: 11,
    priority: 1,
    name: "Vercel Blog",
    slug: "vercel-blog",
    siteUrl: "https://vercel.com/blog",
    feedUrl: "https://vercel.com/atom",
    kind: "rss" as const,
    category: "Web",
    quality: "primary" as const,
    description: "Frontend infrastructure, Next.js, AI SDK, web performance, and platform engineering.",
    tags: ["web", "Next.js", "AI SDK", "frontend"],
  },
  {
    rank: 12,
    priority: 1,
    name: "Cloudflare Blog",
    slug: "cloudflare-blog",
    siteUrl: "https://blog.cloudflare.com/",
    feedUrl: "https://blog.cloudflare.com/rss/",
    kind: "rss" as const,
    category: "Infrastructure",
    quality: "primary" as const,
    description: "Internet infrastructure, networking, security, distributed systems, and developer platform engineering.",
    tags: ["infrastructure", "security", "networking", "distributed systems"],
  },
  {
    rank: 13,
    priority: 1,
    name: "Netflix TechBlog",
    slug: "netflix-techblog",
    siteUrl: "https://netflixtechblog.com/",
    feedUrl: "https://netflixtechblog.com/feed",
    kind: "rss" as const,
    category: "Engineering",
    quality: "primary" as const,
    description: "Large-scale systems, data, media, reliability, and software engineering at Netflix.",
    tags: ["engineering", "distributed systems", "data", "reliability"],
  },
  {
    rank: 14,
    priority: 2,
    name: "Slack Engineering",
    slug: "slack-engineering",
    siteUrl: "https://slack.engineering/",
    feedUrl: "https://slack.engineering/feed/",
    kind: "rss" as const,
    category: "Engineering",
    quality: "primary" as const,
    description: "Backend, mobile, infrastructure, data, reliability, and product engineering at Slack.",
    tags: ["engineering", "backend", "reliability", "data"],
  },
  {
    rank: 15,
    priority: 2,
    name: "Shopify Engineering",
    slug: "shopify-engineering",
    siteUrl: "https://shopify.engineering/",
    kind: "web" as const,
    category: "Engineering",
    quality: "primary" as const,
    description: "Commerce-scale systems, Ruby, databases, infrastructure, and developer productivity.",
    tags: ["engineering", "Ruby", "databases", "infrastructure"],
  },
  {
    rank: 16,
    priority: 2,
    name: "Dropbox Tech",
    slug: "dropbox-tech",
    siteUrl: "https://dropbox.tech/",
    feedUrl: "https://dropbox.tech/feed",
    kind: "rss" as const,
    category: "Engineering",
    quality: "primary" as const,
    description: "Storage, sync, databases, networking, machine learning, and infrastructure engineering.",
    tags: ["engineering", "storage", "distributed systems", "infrastructure"],
  },
  {
    rank: 17,
    priority: 2,
    name: "Uber Engineering",
    slug: "uber-engineering",
    siteUrl: "https://www.uber.com/blog/engineering/",
    kind: "web" as const,
    category: "Engineering",
    quality: "primary" as const,
    description: "Distributed systems, data platforms, mapping, machine learning, and reliability at Uber.",
    tags: ["engineering", "distributed systems", "data", "machine learning"],
  },
  {
    rank: 18,
    priority: 2,
    name: "Stripe Engineering",
    slug: "stripe-engineering",
    siteUrl: "https://stripe.com/blog/engineering",
    kind: "web" as const,
    category: "Engineering",
    quality: "primary" as const,
    description: "Payments infrastructure, APIs, databases, reliability, and developer tooling at Stripe.",
    tags: ["engineering", "payments", "APIs", "databases"],
  },
  {
    rank: 19,
    priority: 2,
    name: "Mozilla Hacks",
    slug: "mozilla-hacks",
    siteUrl: "https://hacks.mozilla.org/",
    feedUrl: "https://hacks.mozilla.org/feed/",
    kind: "rss" as const,
    category: "Web",
    quality: "primary" as const,
    description: "Browser engineering, web standards, JavaScript, Firefox, and open web technology.",
    tags: ["web", "browser", "JavaScript", "standards"],
  },
  {
    rank: 20,
    priority: 2,
    name: "WebKit Blog",
    slug: "webkit-blog",
    siteUrl: "https://webkit.org/blog/",
    feedUrl: "https://webkit.org/feed/",
    kind: "rss" as const,
    category: "Web",
    quality: "primary" as const,
    description: "WebKit browser engine features, standards, performance, and platform engineering.",
    tags: ["web", "browser", "standards", "performance"],
  },
  {
    rank: 21,
    priority: 2,
    name: "Microsoft Developer Blogs",
    slug: "microsoft-developer-blogs",
    siteUrl: "https://devblogs.microsoft.com/",
    feedUrl: "https://devblogs.microsoft.com/feed/",
    kind: "rss" as const,
    category: "Developer Tools",
    quality: "primary" as const,
    description: "Developer platform updates across .NET, Azure tooling, languages, IDEs, and engineering.",
    tags: ["developer tools", ".NET", "Azure", "languages"],
  },
  {
    rank: 22,
    priority: 2,
    name: "JetBrains Blog",
    slug: "jetbrains-blog",
    siteUrl: "https://blog.jetbrains.com/",
    feedUrl: "https://blog.jetbrains.com/feed/",
    kind: "rss" as const,
    category: "Developer Tools",
    quality: "primary" as const,
    description: "IDEs, programming languages, developer productivity, tooling, and software engineering.",
    tags: ["developer tools", "IDEs", "languages", "productivity"],
  },
  {
    rank: 23,
    priority: 2,
    name: "AWS Architecture Blog",
    slug: "aws-architecture-blog",
    siteUrl: "https://aws.amazon.com/blogs/architecture/",
    feedUrl: "https://aws.amazon.com/blogs/architecture/feed/",
    kind: "rss" as const,
    category: "Cloud",
    quality: "primary" as const,
    description: "Cloud architecture, distributed systems, serverless, data, resilience, and AWS design patterns.",
    tags: ["cloud", "architecture", "AWS", "distributed systems"],
  },
  {
    rank: 24,
    priority: 2,
    name: "AWS Security Blog",
    slug: "aws-security-blog",
    siteUrl: "https://aws.amazon.com/blogs/security/",
    feedUrl: "https://aws.amazon.com/blogs/security/feed/",
    kind: "rss" as const,
    category: "Security",
    quality: "primary" as const,
    description: "Cloud security, identity, threat detection, cryptography, and AWS security engineering.",
    tags: ["security", "cloud", "AWS", "identity"],
  },
  {
    rank: 25,
    priority: 1,
    name: "Kubernetes Blog",
    slug: "kubernetes-blog",
    siteUrl: "https://kubernetes.io/blog/",
    feedUrl: "https://kubernetes.io/feed.xml",
    kind: "rss" as const,
    category: "Cloud Native",
    quality: "primary" as const,
    description: "Official Kubernetes releases, architecture, operations, security, and ecosystem updates.",
    tags: ["Kubernetes", "cloud native", "containers", "infrastructure"],
  },
  {
    rank: 26,
    priority: 2,
    name: "Docker Blog",
    slug: "docker-blog",
    siteUrl: "https://www.docker.com/blog/",
    feedUrl: "https://www.docker.com/blog/feed/",
    kind: "rss" as const,
    category: "Cloud Native",
    quality: "primary" as const,
    description: "Containers, developer environments, image tooling, security, and Docker platform updates.",
    tags: ["containers", "Docker", "developer tools", "cloud native"],
  },
  {
    rank: 27,
    priority: 2,
    name: "CNCF Blog",
    slug: "cncf-blog",
    siteUrl: "https://www.cncf.io/blog/",
    kind: "web" as const,
    category: "Cloud Native",
    quality: "primary" as const,
    description: "Cloud native projects, maintainers, platform engineering, Kubernetes ecosystem, and infrastructure.",
    tags: ["cloud native", "Kubernetes", "open source", "platform engineering"],
  },
  {
    rank: 28,
    priority: 2,
    name: "Sentry Blog",
    slug: "sentry-blog",
    siteUrl: "https://blog.sentry.io/",
    feedUrl: "https://blog.sentry.io/feed.xml",
    kind: "rss" as const,
    category: "Developer Tools",
    quality: "primary" as const,
    description: "Application observability, debugging, performance, OpenTelemetry, and engineering practices.",
    tags: ["observability", "debugging", "OpenTelemetry", "engineering"],
  },
  {
    rank: 29,
    priority: 2,
    name: "Tailscale Blog",
    slug: "tailscale-blog",
    siteUrl: "https://tailscale.com/blog",
    kind: "web" as const,
    category: "Networking",
    quality: "primary" as const,
    description: "Networking, identity, zero trust, WireGuard, infrastructure, and practical security engineering.",
    tags: ["networking", "security", "WireGuard", "infrastructure"],
  },
  {
    rank: 30,
    priority: 2,
    name: "Fly.io Blog",
    slug: "fly-io-blog",
    siteUrl: "https://fly.io/blog/",
    feedUrl: "https://fly.io/blog/feed.xml",
    kind: "rss" as const,
    category: "Infrastructure",
    quality: "primary" as const,
    description: "Distributed applications, databases, networking, runtimes, and infrastructure engineering.",
    tags: ["infrastructure", "distributed systems", "databases", "networking"],
  },
  {
    rank: 31,
    priority: 2,
    name: "GitLab Blog",
    slug: "gitlab-blog",
    siteUrl: "https://about.gitlab.com/blog/",
    feedUrl: "https://about.gitlab.com/atom.xml",
    kind: "rss" as const,
    category: "DevOps",
    quality: "primary" as const,
    description: "DevOps, CI/CD, software supply chain, security, AI-assisted development, and platform engineering.",
    tags: ["DevOps", "CI/CD", "security", "developer tools"],
  },
  {
    rank: 32,
    priority: 2,
    name: "Supabase Blog",
    slug: "supabase-blog",
    siteUrl: "https://supabase.com/blog",
    kind: "web" as const,
    category: "Databases",
    quality: "primary" as const,
    description: "Postgres, backend infrastructure, realtime systems, auth, storage, and developer platform updates.",
    tags: ["Postgres", "databases", "backend", "developer tools"],
  },
  {
    rank: 33,
    priority: 2,
    name: "Grafana Labs Blog",
    slug: "grafana-labs-blog",
    siteUrl: "https://grafana.com/blog/",
    kind: "web" as const,
    category: "Observability",
    quality: "primary" as const,
    description: "Metrics, logs, traces, OpenTelemetry, observability architecture, and production operations.",
    tags: ["observability", "OpenTelemetry", "Grafana", "SRE"],
  },
  {
    rank: 34,
    priority: 1,
    name: "Rust Blog",
    slug: "rust-blog",
    siteUrl: "https://blog.rust-lang.org/",
    feedUrl: "https://blog.rust-lang.org/feed.xml",
    kind: "rss" as const,
    category: "Programming Languages",
    quality: "primary" as const,
    description: "Official Rust language releases, tooling, compiler, ecosystem, and project updates.",
    tags: ["Rust", "programming languages", "compiler", "open source"],
  },
  {
    rank: 35,
    priority: 1,
    name: "Go Blog",
    slug: "go-blog",
    siteUrl: "https://go.dev/blog/",
    feedUrl: "https://go.dev/blog/feed.atom",
    kind: "rss" as const,
    category: "Programming Languages",
    quality: "primary" as const,
    description: "Official Go language, runtime, tooling, performance, and ecosystem articles.",
    tags: ["Go", "programming languages", "runtime", "backend"],
  },
  {
    rank: 36,
    priority: 1,
    name: "Node.js Blog",
    slug: "nodejs-blog",
    siteUrl: "https://nodejs.org/en/blog",
    feedUrl: "https://nodejs.org/en/feed/blog.xml",
    kind: "rss" as const,
    category: "Programming Languages",
    quality: "primary" as const,
    description: "Official Node.js releases, runtime updates, security notices, and project news.",
    tags: ["Node.js", "JavaScript", "runtime", "backend"],
  },
  {
    rank: 37,
    priority: 2,
    name: "Python Insider",
    slug: "python-insider",
    siteUrl: "https://blog.python.org/",
    feedUrl: "https://blog.python.org/feeds/posts/default",
    kind: "rss" as const,
    category: "Programming Languages",
    quality: "primary" as const,
    description: "Official Python release, governance, security, and core development announcements.",
    tags: ["Python", "programming languages", "releases", "open source"],
  },
  {
    rank: 38,
    priority: 2,
    name: "Chromium Blog",
    slug: "chromium-blog",
    siteUrl: "https://blog.chromium.org/",
    feedUrl: "https://blog.chromium.org/feeds/posts/default",
    kind: "rss" as const,
    category: "Web",
    quality: "primary" as const,
    description: "Chrome and Chromium platform features, browser security, performance, and web capabilities.",
    tags: ["browser", "Chrome", "web", "security"],
  },
  {
    rank: 39,
    priority: 1,
    name: "Google Security Blog",
    slug: "google-security-blog",
    siteUrl: "https://security.googleblog.com/",
    feedUrl: "https://feeds.feedburner.com/GoogleOnlineSecurityBlog",
    kind: "rss" as const,
    category: "Security",
    quality: "primary" as const,
    description: "First-party Google security research, vulnerability work, privacy, and platform defenses.",
    tags: ["security", "vulnerabilities", "privacy", "research"],
  },
  {
    rank: 40,
    priority: 1,
    name: "Google Project Zero",
    slug: "google-project-zero",
    siteUrl: "https://googleprojectzero.blogspot.com/",
    feedUrl: "https://googleprojectzero.blogspot.com/feeds/posts/default",
    kind: "rss" as const,
    category: "Security Research",
    quality: "expert" as const,
    description: "Deep vulnerability research, exploitation techniques, and zero-day analysis from Project Zero.",
    tags: ["security", "vulnerabilities", "exploitation", "research"],
  },
  {
    rank: 41,
    priority: 1,
    name: "Trail of Bits",
    slug: "trail-of-bits",
    siteUrl: "https://blog.trailofbits.com/",
    feedUrl: "https://blog.trailofbits.com/feed/",
    kind: "rss" as const,
    category: "Security Research",
    quality: "expert" as const,
    description: "Software security research, audits, cryptography, compilers, and security tooling.",
    tags: ["security", "research", "cryptography", "tooling"],
  },
  {
    rank: 42,
    priority: 2,
    name: "Krebs on Security",
    slug: "krebs-on-security",
    siteUrl: "https://krebsonsecurity.com/",
    feedUrl: "https://krebsonsecurity.com/feed/",
    kind: "rss" as const,
    category: "Security",
    quality: "expert" as const,
    description: "Independent reporting on cybercrime, breaches, fraud, threat actors, and security operations.",
    tags: ["security", "cybercrime", "breaches", "threats"],
  },
  {
    rank: 43,
    priority: 2,
    name: "Stack Overflow Blog",
    slug: "stack-overflow-blog",
    siteUrl: "https://stackoverflow.blog/",
    feedUrl: "https://stackoverflow.blog/feed/",
    kind: "rss" as const,
    category: "Software Development",
    quality: "publication" as const,
    description: "Software development, developer careers, engineering practice, AI coding, and industry analysis.",
    tags: ["software development", "developers", "AI coding", "engineering"],
  },
  {
    rank: 44,
    priority: 2,
    name: "InfoQ",
    slug: "infoq",
    siteUrl: "https://www.infoq.com/",
    kind: "web" as const,
    category: "Software Architecture",
    quality: "publication" as const,
    description: "Architecture, cloud, DevOps, AI engineering, programming languages, and practitioner-focused news.",
    tags: ["architecture", "DevOps", "cloud", "AI engineering"],
  },
  {
    rank: 45,
    priority: 2,
    name: "Ars Technica",
    slug: "ars-technica",
    siteUrl: "https://arstechnica.com/",
    feedUrl: "https://feeds.arstechnica.com/arstechnica/index",
    kind: "rss" as const,
    category: "Technology",
    quality: "publication" as const,
    description: "Technology, science, security, computing platforms, policy, and detailed technical reporting.",
    tags: ["technology", "science", "security", "computing"],
  },
  {
    rank: 46,
    priority: 3,
    name: "TechCrunch",
    slug: "techcrunch",
    siteUrl: "https://techcrunch.com/",
    feedUrl: "https://techcrunch.com/feed/",
    kind: "rss" as const,
    category: "Startups",
    quality: "publication" as const,
    description: "Technology companies, startups, venture funding, products, AI, and industry developments.",
    tags: ["startups", "technology", "AI", "venture"],
  },
  {
    rank: 47,
    priority: 2,
    name: "MIT Technology Review",
    slug: "mit-technology-review",
    siteUrl: "https://www.technologyreview.com/",
    feedUrl: "https://www.technologyreview.com/feed/",
    kind: "rss" as const,
    category: "Emerging Tech",
    quality: "publication" as const,
    description: "AI, computing, biotechnology, climate, science, and emerging technology analysis.",
    tags: ["emerging tech", "AI", "science", "computing"],
  },
  {
    rank: 48,
    priority: 2,
    name: "IEEE Spectrum",
    slug: "ieee-spectrum",
    siteUrl: "https://spectrum.ieee.org/",
    feedUrl: "https://spectrum.ieee.org/feeds/feed.rss",
    kind: "rss" as const,
    category: "Engineering",
    quality: "publication" as const,
    description: "Engineering, robotics, semiconductors, AI, computing, electronics, and applied research.",
    tags: ["engineering", "robotics", "semiconductors", "AI"],
  },
  {
    rank: 49,
    priority: 1,
    name: "Hacker News",
    slug: "hacker-news",
    siteUrl: "https://news.ycombinator.com/",
    apiUrl: "https://hacker-news.firebaseio.com/v0/",
    kind: "api" as const,
    category: "Community",
    quality: "community" as const,
    description: "Developer and startup community discussion with points and comment context for major stories.",
    tags: ["community", "engineering", "startups", "discussion"],
  },
  {
    rank: 50,
    priority: 2,
    name: "Lobsters",
    slug: "lobsters",
    siteUrl: "https://lobste.rs/",
    feedUrl: "https://lobste.rs/rss",
    kind: "rss" as const,
    category: "Community",
    quality: "community" as const,
    description: "Focused computing community covering programming, systems, security, research, and engineering.",
    tags: ["community", "programming", "systems", "security"],
  },
] as const;
