export const recommendedSources = [
  {
    rank: 1,
    name: "OpenAI News",
    slug: "openai-news",
    siteUrl: "https://openai.com/news/",
    kind: "web" as const,
    category: "AI",
  },
  {
    rank: 2,
    name: "Anthropic News",
    slug: "anthropic-news",
    siteUrl: "https://www.anthropic.com/news",
    kind: "web" as const,
    category: "AI",
  },
  {
    rank: 3,
    name: "Google DeepMind",
    slug: "google-deepmind",
    siteUrl: "https://deepmind.google/blog/",
    kind: "web" as const,
    category: "AI Research",
  },
  {
    rank: 4,
    name: "GitHub Blog",
    slug: "github-blog",
    siteUrl: "https://github.blog/",
    feedUrl: "https://github.blog/feed/",
    kind: "rss" as const,
    category: "Engineering",
  },
  {
    rank: 5,
    name: "Hacker News",
    slug: "hacker-news",
    siteUrl: "https://news.ycombinator.com/",
    apiUrl: "https://hacker-news.firebaseio.com/v0/",
    kind: "api" as const,
    category: "Community",
  },
  {
    rank: 6,
    name: "Vercel Blog",
    slug: "vercel-blog",
    siteUrl: "https://vercel.com/blog",
    feedUrl: "https://vercel.com/atom",
    kind: "rss" as const,
    category: "Web",
  },
  {
    rank: 7,
    name: "Cloudflare Blog",
    slug: "cloudflare-blog",
    siteUrl: "https://blog.cloudflare.com/",
    feedUrl: "https://blog.cloudflare.com/rss/",
    kind: "rss" as const,
    category: "Infrastructure",
  },
  {
    rank: 8,
    name: "Ars Technica",
    slug: "ars-technica",
    siteUrl: "https://arstechnica.com/",
    feedUrl: "https://feeds.arstechnica.com/arstechnica/index",
    kind: "rss" as const,
    category: "Technology",
  },
  {
    rank: 9,
    name: "TechCrunch",
    slug: "techcrunch",
    siteUrl: "https://techcrunch.com/",
    feedUrl: "https://techcrunch.com/feed/",
    kind: "rss" as const,
    category: "Startups",
  },
  {
    rank: 10,
    name: "MIT Technology Review",
    slug: "mit-technology-review",
    siteUrl: "https://www.technologyreview.com/",
    feedUrl: "https://www.technologyreview.com/feed/",
    kind: "rss" as const,
    category: "Emerging Tech",
  },
] as const;
